# Generated by Django 5.2.7 on 2025-11-12 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioimages',
            name='image',
            field=models.ImageField(default=0, upload_to='portfolio/'),
            preserve_default=False,
        ),
    ]
