# Generated by Django 5.2.7 on 2025-11-19 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio_app', '0002_portfolioimages_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='portfoliofiles/'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
